---
- name: add the redpanda repo
  shell: |
    curl -1sLf {{ redpanda_repo_script }} | sudo -E bash

- name: install redpanda from repository
  apt:
    name:
      - redpanda{{ '' if redpanda_version=='latest' else '=' + redpanda_version }}
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result
  when: ansible_os_family == 'Debian'

- name: install redpanda from repository
  yum:
    name:
      - redpanda{{ '' if redpanda_version=='latest' else '-' + redpanda_version }}
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result
  when: ansible_os_family == 'RedHat'

- name: set data dir file perms
  file:
    path: "{{ redpanda_data_directory }}"
    owner: redpanda
    group: redpanda
