# attempt to do a rolling, serial restart by putting each node into maintenance
# mode, restarting, and putting it back into service. This is throttled to allow
# only one node out of service at a time.
#
- name: Enable Maintenance Mode
  ansible.builtin.shell:
    cmd: "rpk cluster maintenance enable {{ node_id }} --wait"
  when:
   - restart_required
   - inventory_hostname == cluster_host

# We need to (actually) generate the node config once the node is in MM, otherwise the `rpk cluster maintenance` command
# will fail
- name: Generate Node config - post-bootstrap runs
  ansible.builtin.template:
    src: "redpanda.yml"
    dest: "/etc/redpanda/redpanda.yaml"
    owner: redpanda
    group: redpanda
  register: nodeconfig_result
  when:
    - is_initialized
    - inventory_hostname == cluster_host

- name: Restart Process
  ansible.builtin.shell:
    cmd: "systemctl restart redpanda"
  when:
   - restart_required
   - inventory_hostname == cluster_host

- name: Disable Maintenance Mode
  ansible.builtin.shell:
    cmd: "rpk cluster maintenance disable {{ node_id }}"
  when:
   - restart_required
   - inventory_hostname == cluster_host
