- hosts: redpanda[0]
  tasks:
  - name: generate the redpanda grafana dashboard
    shell: |
      rpk generate grafana-dashboard --datasource prometheus --metrics-endpoint 'http://{{hostvars[inventory_hostname].private_ip}}:9644/metrics' > '/tmp/redpanda-grafana.json'

  - name: fetch grafana dashboard
    fetch:
      src: /tmp/redpanda-grafana.json
      dest: '{{ playbook_dir }}/grafana_dashboards/redpanda-grafana.json'
      flat: yes


- hosts: monitor
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "redpanda"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, ['ansible_default_ipv4','address']) | map('regex_replace', '^(.*)$','\\1:9644') | list  }}"
      - job_name: "node"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, ['ansible_default_ipv4','address']) | map('regex_replace', '^(.*)$','\\1:9100') | list  }}"

- hosts: monitor
  roles:
  - cloudalchemy.grafana
  vars:
    grafana_version: latest
    grafana_security:
      admin_user: admin
      admin_password: "{{ grafana_admin_pass | default('enter_your_secure_password', true) }}"
    grafana_datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: 'http://localhost:9090'
      basicAuth: false
    grafana_dashboards_dir: '{{ playbook_dir }}/grafana_dashboards'

- hosts: localhost
  tasks:
  - file:
      path: '{{ playbook_dir }}/grafana_dashboards/redpanda-grafana.json'
      state: absent
