- hosts: redpanda
  tasks:

  - name: Test hosts list
    debug:
      msg:
      - "ipv4            : {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      - "private ip      : {{ hostvars[inventory_hostname]['private_ip'] }}"
      - "ansible_hostname: {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
      - "ansible_fqdn    : {{ hostvars[inventory_hostname]['ansible_fqdn'] }}"

  - name: create redpanda user if it doesn't exist already
    ansible.builtin.user:
      name: redpanda
      system: true

  - name: ensure /etc/redpanda/certs exists
    ansible.builtin.file:
      path: "{{ redpanda_certs_dir }}"
      state: directory
      owner: redpanda
      group: redpanda
      mode: 0755

  - name: Copy node template
    ansible.builtin.template:
      src: node.conf.tpl
      dest: "{{ redpanda_certs_dir }}/node.conf"
      owner: redpanda
      group: redpanda

  - name: Install openssl
    ansible.builtin.package:
      name: openssl
      state: present

  - name: Generate an OpenSSH keypair on {{ansible_hostname}}
    ansible.builtin.command:
      creates: "{{ redpanda_key_file }}"
      chdir: "{{ redpanda_certs_dir }}"
      cmd: openssl genrsa -out node.key 2048

  - name: Generate a Certificate Signing Request on {{ansible_hostname}}
    ansible.builtin.command:
      creates: "{{ redpanda_csr_file }}"
      chdir: "{{ redpanda_certs_dir }}"
      cmd: openssl req -new -config node.conf -key node.key -out node.csr -batch

  - name: CHOWN to redpanda
    ansible.builtin.file:
      path: "{{ redpanda_certs_dir }}"
      state: directory
      owner: redpanda
      group: redpanda
      recurse: yes

  - name: Fetch CSRs
    fetch:
      src: "{{ redpanda_csr_file }}"
      dest: tls/certs/{{ansible_hostname}}/node.csr
      flat: yes

  - name: Dummy to import role so that we can use its default variables
    import_role:
      name: redpanda_broker
    when: False