- hosts: redpanda[0]
  tasks:
    - name: Establish if redpanda grafana dashboard file exists
      ansible.builtin.stat:
        path: /tmp/redpanda-grafana.json
      register: dashboard

    - name: generate the redpanda grafana dashboard
      ansible.builtin.shell: |
        rpk generate grafana-dashboard --datasource prometheus --metrics-endpoint 'http{{ 's' if tls|default(false) else '' }}://{{hostvars[inventory_hostname].private_ip}}:9644/public_metrics' > '/tmp/redpanda-grafana.json'
      when: not dashboard.stat.exists

    - name: fetch grafana dashboard
      ansible.builtin.fetch:
        src: /tmp/redpanda-grafana.json
        dest: '{{ playbook_dir }}/grafana_dashboards/redpanda-grafana.json'
        flat: true

- hosts: monitor
  tasks:
    - name: install deps
      ansible.builtin.package:
        name: python3-jmespath
        state: present

- hosts: monitor
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "redpanda"
        metrics_path: "/public_metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9644') | list  }}"
      - job_name: "node"
        metrics_path: "/public_metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9100') | list  }}"

- hosts: monitor
  roles:
    - cloudalchemy.grafana
  vars:
    grafana_version: 9.0.0
    grafana_security:
      admin_user: admin
      admin_password: "{{ grafana_admin_pass | default('enter_your_secure_password', true) }}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards_dir: '{{ playbook_dir }}/grafana_dashboards'

- hosts: localhost
  tasks:
    - ansible.builtin.file:
        path: '{{ playbook_dir }}/grafana_dashboards/redpanda-grafana.json'
        state: absent
