# Creates a TLS enabled cluster with local CA in artifacts/ca for testing purposes
# !!! WARNING !!!
# If you intend to use this for a production cluster you will need to set handle_certs to false and provide your own certs
# Using our demo certificate authority for production is not recommended, and is intended only for testing and proof of concepts.
# Redpanda encourages you to integrate with your corporate certificate management setup.
# variables
# root_ca_dir: location of our demo cert authority
# handle_certs: when false, disables all activity related to our demo CA
# enable_tls: when true, adds the tls template to the /etc/redpanda/redpanda.yml file
# advertise_public_ips : causes the cluster to set a public ip on advertised_kafka_api, allowing access to the cluster from the public internet
---
- name: Provision tiered storage cluster
  hosts: redpanda
  vars:
    root_ca_dir: "{{ playbook_dir }}/tls/ca"
    enable_tls: true
    advertise_public_ips: true
    create_demo_certs: true
    handle_cert_install: true
    cloud_storage_credentials_source: "AWS instance metadata"
    cloud_storage_region: "us-west-2"
    tiered_storage_bucket_name: "rp-devex-cicd-bucket"
  tasks:
    - name: Install and configure CA certs for running tls
      ansible.builtin.include_role:
        name: demo_certs
    - name: Install and start redpanda
      ansible.builtin.include_role:
        name: redpanda_broker
      when: not skip_node | default(false) | bool
