# This playbook provisions a Redpanda cluster with no bells or whistles for evaluation purposes
# variables
# advertise_public_ips : causes the cluster to set a public ip on advertised_kafka_api, allowing access to the cluster from the public internet
---
- name: Provision nodes
  hosts: redpanda
  vars:
    advertise_public_ips: true
    redpanda_version: latest
  tasks:
    - name: Install system prereqs
      ansible.builtin.include_role:
        name: redpanda.cluster.system_setup
    - name: Install and start redpanda
      ansible.builtin.include_role:
        name: redpanda.cluster.redpanda_broker
      when: not skip_node | default(false) | bool

- name: Provision redpanda console
  hosts: client
  vars:
    advertise_public_ips: true
    redpanda_version: latest
    install_console: true
  tasks:
    - name: Install and start redpanda console
      ansible.builtin.include_role:
        name: redpanda.cluster.redpanda_broker
      when: not skip_node | default(false) | bool
